### ISSUE TITLE
From Holistics Engineering team

### ISSUE THREAD

**Issue by phiendp** [duonghds/ledis#1]
Hi,

Thank you for taking your time to work on this assignment. We really appreciate that!

We are reviewing your assignment and will get back to you soon. In the meantime, can you update the README to have a proper introduction to the project (especially a list of available endpoints), and also include some instructions on how to set up the project?

All the best!

**Comment by duonghoang1** [comment]
OMG! seem like i write README file on other branch and forgot to merge/push to hub. I will check and update soon.

**Comment by duonghds** [comment]
Hi anh Phien,

I have already updated README file with detalied information about Ledis project :D
